### DISCUSSION TITLE
Using Split in YAML

### DISCUSSION THREAD

**Discussion by chiragsanghavi** [KaotoIO/kaoto#2079] [Q&A] [answered]
When I use split in YAML and add steps - the expression part of split is moved to the end "with" steps layered in between.
Is that expected?

```
- route:
    id: route-2386
    from:
      id: from-2734
      uri: file
      parameters:
        directoryName: C:\work\camel-demos\NDJSONtoGCP\in
      steps:
        - log:
            id: log-1911
            message: ${headers}
        - doTry:
            id: doTry-1693
            steps:
              - log:
                  id: log-1382
                  message: ${headers}
              - split:
                  id: split-2274
                  steps:
                    - log:
                        id: log-2323
                        message: ${headers}
                  expression:
                    tokenize:
                      token: \n
            doCatch:
              - id: doCatch-4690
                steps:
                  - log:
                      id: log-4042
                      message: ${body}
                exception:
                  - java.lang.NullPointerException
            doFinally:
              id: doFinally-3347
              steps: []
```

I would have expected it to do:
```
              - split:
                  id: split-2274
                  tokenize:
                    token: \n
                  steps:
                    - log:
                        id: log-2323
                        message: "${headers}"

```
