### ISSUE TITLE
Avoid serializing empty strings

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1022]
### Describe the Bug

In case a string field is touched and later on clean, the resulting YAML looks like the following:
```yaml
property: ""
```

This is an issue for the expression field in which the resultType property gets an empty string and it makes the route to fail.
```yaml
              - expression:
                  simple:
                    expression: ${body[0]}
                    resultType: ""
```

### Steps to Reproduce the Bug or Issue

1. Using a `setHeader` EIP, edit the `resultType` property
2. Clean the field
3. Check how the `resultType` property is now an empty string

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
