### ISSUE TITLE
Inserting a `doCatch` generates an invalid Camel structure

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1025]
### Describe the Bug

In `doTry`, inserting a `doCatch` generates an invalid Camel structure

### Steps to Reproduce the Bug or Issue

1. Start with a sample Camel route
2. Insert a `doTry` processor
3. Insert an additional `doCatch`
4. Notice how the structure now it's not correct:
```yaml
// WRONG
        - doTry:
            id: doTry-1935
            steps:
              - log:
                  id: log-1117
                  message: ${body}
            doCatch:
              - doCatch:
                  id: doCatch-3685
              - id: doCatch-2562
                steps: []
            doFinally:
              id: doFinally-3679
              steps: []
```

Whereas it should be:
```yaml
// RIGHT
        - doTry:
            id: doTry-1935
            steps:
              - log:
                  id: log-1117
                  message: ${body}
            doCatch:
              - id: doCatch-2562
                steps: []
              - id: doCatch-3685
                steps: []
            doFinally:
              id: doFinally-3679
              steps: []
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
