### ISSUE TITLE
Log EIP `message` property is not market as required

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1104]
### Describe the Bug

In the [Camel YAML DSL](https://github.com/apache/camel/blob/5efbaa0bd38aee8d44f106581d7588dc9e64f675/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json#L2639-L2646), `message` is marked as required.
![image](https://github.com/KaotoIO/kaoto/assets/16512618/8969c5cf-294b-4f0c-9f06-9e13dd38ca29)

This is also true for [the EIP definition](https://github.com/apache/camel/blob/5efbaa0bd38aee8d44f106581d7588dc9e64f675/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/log.json#L18).

Unfortunately, neither in the canvas nor the form, is respected.
![image](https://github.com/KaotoIO/kaoto/assets/16512618/8a2f05dd-2df4-4346-ae38-441b065c6b43)
![image](https://github.com/KaotoIO/kaoto/assets/16512618/ac896899-94f2-4d69-98f8-0562bd37c5bf)

### Steps to Reproduce the Bug or Issue

Using the following Route

```yaml
- route:
    id: route-1208
    from:
      id: from-8631
      uri: timer:template
      parameters:
        period: "1000"
      steps:
        - log:
            id: log-3385
```

Notice how the `message` field is not required.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
