### ISSUE TITLE
`multiValue` is not supported

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1428]
The `kafka` component, has [an `additionalProperties` parameter](https://github.com/apache/camel/blob/d95de5d5da3a1ce69504784f6194f897b55e96df/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/kafka.json#L161) that is not supported in Kaoto.

The `multiValue` property should be used to signal that the parameters should be prefixed like the following:
```
parameters:
  prefix.param1: value
  prefix.param2: value
  prefix.param3: value
```
