### ISSUE TITLE
Typing full URI in Endpoint's name generates bad YAML

### ISSUE THREAD

**Issue by brunoNetId** [KaotoIO/kaoto#1429]
### Describe the Bug

YAML supports both the syntax of a full URI with parameters and also, a more YAML structured format where parameters are independent from the URI.

A user may try to use Kaoto to force the parameters in the URI by typing them in the component's name field in the configuration pane.

This results on Kaoto generating bad YAML as shown below.

### Steps to Reproduce the Bug or Issue

Try configuring a Timer action as follows (see image):
![image](https://github.com/user-attachments/assets/ed39848d-834a-4815-877f-d8443065331f)

The source code generated will be similar to:
```yaml
- route:
    id: route-1765
    from:
      uri: timer:yaml?repeatCount=1
      parameters:
        r: ""
        re: ""
        rep: ""
        repe: ""
        repea: ""
        repeat: ""
        repeatC: ""
        repeatCo: ""
        repeatCou: ""
        repeatCoun: ""
        repeatCount: ""
        repeatCount-: ""
      steps:
        - setBody:
            simple: Hello Camel from ${routeId}
        - log: ${body}
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
