### ISSUE TITLE
Provide a template for `removeHeaders` EIP

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1541]
### Please describe the feature that you want to propose

When adding a `removeHeaders` EIP, most of the time we would like to remove them all. The goal for this issue is to provide a pattern of `*`:

```yaml
        - removeHeaders:
            id: removeHeaders-4218
            pattern: "*"
```
