### ISSUE TITLE
`otherwise` and `doFinally` are wrongly generated

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#1674]
### Please describe the task that needs to be done

When adding one of those branches, the EIP gets badly generated:
```yaml
        - choice:
            id: choice-1461
            otherwise:
              otherwise:
                id: otherwise-4089
```
