### ISSUE TITLE
An attribute node cannot be created after a child of the containing element.

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#1728]
### Describe the Bug

When creating attribute mapping - in case the mapping is created after there were other mappings created, the resulting mapping throws at runtime following error, due to  the order the attribute mapping was inserted (at the end):

```
net.sf.saxon.event.NoOpenStartTagException: An attribute node (OrderId) cannot be created after a child of the containing element. Most recent element start tag was output at line 17 of module classpath:route-9e42-kaoto-datamapper-2411.xsl
```

the route used:
```
- route:
    id: route-9e42
    from:
      id: from-52f6
      uri: timer
      parameters:
        period: "5000"
        timerName: banks
      steps:
        - to:
            id: to-57d1
            uri: http
            parameters:
              httpUri: https://random-data-api.com/api/v2/banks?response_type=xml
        - step:
            id: kaoto-datamapper-2411
            steps:
              - to:
                  id: kaoto-datamapper-xslt-6474
                  uri: xslt-saxon:route-9e42-kaoto-datamapper-2411.xsl
                  parameters: {}
        - log:
            id: log-156f
            message: ${prettyBody}
    nodePrefixId: route-ecf
```

the mapping with the issue:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <ShipOrder xmlns="io.kaoto.datamapper.poc.test">
            <ShipTo xmlns="">
                <Name>
                    <xsl:value-of select="/hash/uid"/>
                </Name>
                <Address>
                    <xsl:value-of select="/hash/account-number"/>
                </Address>
                <City>
                    <xsl:value-of select="/hash/bank-name"/>
                </City>
                <Country>
                    <xsl:value-of select="/hash/swift-bic"/>
                </Country>
            </ShipTo>
            <xsl:attribute name="OrderId">
                <xsl:value-of select="/hash/id"/>
            </xsl:attribute>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>
```

### Steps to Reproduce the Bug or Issue

1. create mapping 
2. make sure, the attribute mapping is at the end of the xsl - create other mappings prior to the attribute mapping
3. try to run with jbang
4. see the error 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
