### ISSUE TITLE
Sometimes link are not drawn when reopening Datamapper

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1739]
### Describe the Bug

it occurs with this route:

```yaml
- route:
    id: route-2655
    from:
      uri: timer:yaml
      parameters:
        period: "1000"
      steps:
        - setBody:
            expression:
              simple:
                expression: |-
                  <?xml version="1.0" encoding="UTF-8"?>
                  <shiporder orderid="889923"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="shiporder.xsd">
                  <orderperson>John Smith</orderperson>
                  <shipto>
                  <name>Ola Nordmann</name>
                  <address>Langgt 23</address>
                  <city>4000 Stavanger</city>
                  <country>Norway</country>
                  </shipto>
                  <item>
                  <title>Empire Burlesque</title>
                  <note>Special Edition</note>
                  <quantity>1</quantity>
                  <price>10.90</price>
                  </item>
                  <item>
                  <title>Hide your heart</title>
                  <quantity>1</quantity>
                  <price>9.90</price>
                  </item>
                  </shiporder>
        - to:
            id: to-4174
            uri: log:InfoLogger
            parameters: {}
        - step:
            id: kaoto-datamapper-3455
            steps:
              - to:
                  id: kaoto-datamapper-xslt-1922
                  uri: xslt:route-2655-kaoto-datamapper-3455.xsl
                  parameters: {}
        - to:
            id: to-7858
            uri: log:InfoLogger
            parameters: {}
```
and this xsl:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <shiporder>
            <xsl:attribute name="orderid">
                <xsl:value-of select="/shiporder/@orderid"/>
            </xsl:attribute>
            <orderperson>
                <xsl:value-of select="/shiporder/orderperson"/>
            </orderperson>
            <item>
                <xsl:copy-of select="/shiporder/item"/>
            </item>
        </shiporder>
    </xsl:template>
</xsl:stylesheet>
```

this xsd is used:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="shiporder">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="orderperson" type="xs:string"/>
      <xs:element name="shipto">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="item" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="note" type="xs:string" minOccurs="0"/>
            <xs:element name="quantity" type="xs:positiveInteger"/>
            <xs:element name="price" type="xs:decimal"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="orderid" type="xs:string" use="required"/>
  </xs:complexType>
</xs:element>

</xs:schema> 
```

and I have this .kaoto mapping file:
```json
{
	"route-3984-kaoto-datamapper-1": {
		"sourceBody": {
			"type": "Primitive"
		},
		"sourceParameters": {},
		"targetBody": {
			"type": "Primitive"
		},
		"xsltPath": "kaoto-datamapper-1.xsl"
	},
	"route-3984-kaoto-datamapper-1096": {
		"sourceBody": {
			"type": "XML Schema",
			"filePath": [
				"../../../../note.xsd"
			]
		},
		"sourceParameters": {},
		"targetBody": {
			"type": "XML Schema",
			"filePath": [
				"note.xsd"
			]
		},
		"xsltPath": "kaoto-datamapper-1096.xsl"
	},
	"route-3984-kaoto-datamapper-2269": {
		"sourceBody": {
			"type": "XML Schema",
			"filePath": [
				"../../../../note.xsd"
			]
		},
		"sourceParameters": {},
		"targetBody": {
			"type": "Primitive"
		},
		"xsltPath": "kaoto-datamapper-2269.xsl"
	},
	"route-2655-kaoto-datamapper-3455": {
		"sourceBody": {
			"type": "XML Schema",
			"filePath": [
				"shiporder.xsd"
			]
		},
		"sourceParameters": {},
		"targetBody": {
			"type": "XML Schema",
			"filePath": [
				"shiporder.xsd"
			]
		},
		"xsltPath": "route-2655-kaoto-datamapper-3455.xsl"
	}
}
```

### Steps to Reproduce the Bug or Issue

not sure

### Screenshots or Videos

![edgeNotDrawnOnReopening](https://github.com/user-attachments/assets/2995b1f5-afd4-4493-90c5-5d44e3257f75)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
