### ISSUE TITLE
Line for first source body element is not drawn

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#1763]
### Describe the Bug

Line for first source body element is not drawn

### Steps to Reproduce the Bug or Issue

1. Create a route with a datamapper step such as:
```yaml
- route:
    id: route-3984
    from:
      uri: timer:yaml
      parameters:
        period: "1000"
      steps:
        - setBody:
            simple: Hello Camel from ${routeId}
        - step:
            id: kaoto-datamapper-1
            steps:
              - to:
                  id: to-4074
                  uri: xslt
                  parameters: {}
 ```
2. Open the datamapper
3. Import the schema for source and target:
```xml
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="note">
<xs:complexType>
<xs:sequence>
<xs:element name="to" type="xs:string"/>
<xs:element name="from" type="xs:string"/>
<xs:element name="heading" type="xs:string"/>
<xs:element name="body" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
```
4. drag and drop the first child source element to one of the target
5. Th eline is not drawn

### Screenshots or Videos

![firstLineNotDrawn](https://github.com/user-attachments/assets/02a7f4db-836a-4546-9953-a0a2e2a82432)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
