### ISSUE TITLE
Support exporting Camel route snipet

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#1824]
In order to support KaotoIO/kaoto#1825 , the Data Mapper step needs to be a set of multiple steps wrapped with the `step` EIP.
```yaml
 - step:
     id: kaoto-datamapper-1234
     steps:
       - to:
           uri: xslt:variable-mappings.xsl
       - setVariable:
           name: targetVariable1
           value: ${body}
       - to:
           uri: xslt:body-mappings.xsl
```
