### ISSUE TITLE
Support setting headers/variables

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#1825]
Introduce target document for Camel Message Header and Variables. They produce steps such as `setHeader` and `setVariable` paired with `camel-xslt` step for each. IOW the number of `camel-xslt` step 
will be the number of target documents.

This example sets a variable `targetVariable1`. In order to get the value for that, it needs to process a separate XSLT transformation with `variable-mappings.xsl` as XSLT only produces one output.
```yaml
 - step:
     id: kaoto-datamapper-1234
     steps:
       - to:
           uri: xslt:variable-mappings.xsl
       - setVariable:
           name: targetVariable1
           value: ${body}
       - to:
           uri: xslt:body-mappings.xsl
```
