### ISSUE TITLE
[EIP] CorrelationExpression from the Aggregate EIP is serialised incorrectly

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto#1934]
### Describe the Bug

CorrelationExpression format is invalid according the schema: 
<img width="449" alt="Image" src="https://github.com/user-attachments/assets/5acbb4af-6160-4665-b780-1251d9b5ee69" />

should be:
```yaml
 correlationExpression:
              header:
                expression: hello
```

### Steps to Reproduce the Bug or Issue

1. Create route from visualisation 
2. Add aggregate and set the Correlation Expression
3. See the source code

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
