### ISSUE TITLE
[EIP]:CircuitBreaker's onFallback object is not recognised by Kaoto

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto#1935]
### Describe the Bug

 onFallback object is not recognised by Kaoto. The object is defined in the camel catalog and also in the CamelYamlDSL. 

The problem is that onFallback is defined as a processor and Kaoto is parsing it as element in steps array, which the schema allows, but I believe that's wrong. 

### Steps to Reproduce the Bug or Issue

1. Paste YAML with following example:
```yaml
- route:
    id: route-8014
    from:
      id: from-8738
      uri: timer
      parameters:
        period: "1000"
        timerName: template
      steps:
        - circuitBreaker:
            onFallback:
              id: onFallback-3122
              steps:
                - to:
                    id: to-1309
                    uri: aws-bedrock-agent-runtime
                    parameters: {}
            id: circuitBreaker-3756
           
```
See the visualisation: 

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/921e1f58-54c1-43ee-b064-838b12113a39" />

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
