### ISSUE TITLE
Support `uri` with and without `//`

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#2017]
### Please describe the feature that you want to propose

Currently, Kaoto honors the `syntax` field of components, and some components do not use `//` as a delimiter while still supporting it.

Example of this is are [`ftp`](https://github.com/apache/camel/blob/62b02d09e2a1c7bb7699894c04a7998f99205fad/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/ftp.json#L17) and [`sftp`](https://github.com/apache/camel/blob/62b02d09e2a1c7bb7699894c04a7998f99205fad/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/sftp.json#L17) components:

```
    "syntax": "ftp:host:port\/directoryName",
```

Notice how `//` it's not included in the syntax but still a user could write the URI as:
```yaml
uri: ftp://myHost:myPort/dirName # (not supported by Kaoto)

# vs

uri: ftp:myHost:myPort/dirName # (supported by Kaoto)
```

The goal is to have support for `uri`s using `//` delimiter, even if not specified in the `syntax` field.
