### ISSUE TITLE
URI configuration in Yaml camel route doesn't translate correctly into XML

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#2084]
### Describe the Bug

use e.g. this sample route:
```
- route:
    id: test-route
    from:
      uri: timer:start?period=1000&delay=2000&repeatCount=10
      steps:
        - setBody:
            constant: Initial message
        - to: log:info?showAll=true&multiline=true&logMask=true
        - transform:
            simple: ${body.toUpperCase()}
        - to: file:output?fileName=output.txt&fileExist=Append
```

the resulting XML route looks as follows:
```
<camel>
  <route id="test-route">
    <from uri="timer:start?period=1000&amp;delay=2000&amp;repeatCount=10"/>
    <setBody>
      <constant/>
    </setBody>
    <to/>
    <transform>
      <simple/>
    </transform>
    <to/>
  </route>
</camel>
```

### Steps to Reproduce the Bug or Issue

1. create Camel route with URI config
2. switch to XML
3. see the route is missing some of the URI configs

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]
