### ISSUE TITLE
"[object Object]" when using object properties in bean definition in XML

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#2086]
### Describe the Bug

When trying to specify route, with object properties in beans, the resulting XML route contains `[object Object]` instead of the object property.

Try to use route e.g.:
```
- route:
    id: test-route
    from:
      uri: timer:start?period=1000&delay=2000&repeatCount=10
      steps:
        - setBody:
            constant: Initial message
        - to:
            uri: log
            parameters:
              loggerName: test
- beans:
    - builderClass: test
      constructors:
        objectProperty: {}
      name: test
      properties:
        test: {}
      type: org.apache.camel.spi.ExchangeFormatter

```

The result XML route after the switch looks like this:
```
<camel>
  <route id="test-route">
    <from uri="timer:start?period=1000&amp;delay=2000&amp;repeatCount=10"/>
    <setBody>
      <constant/>
    </setBody>
    <to uri="log:test"/>
  </route>
  <beans>
    <bean name="test" type="org.apache.camel.spi.ExchangeFormatter" builderClass="test">
      <constructors>
        <constructor index="objectProperty" value="[object Object]"/>
      </constructors>
      <properties>
        <property key="test" value="[object Object]"/>
      </properties>
    </bean>
  </beans>
</camel>
```

### Steps to Reproduce the Bug or Issue

1. create a bean with object property
2. switch to XML view
3. see the `[object Object]` instead of the object property

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]
