### ISSUE TITLE
String defined steps are not parsed correctly

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto#2089]
### Describe the Bug

According the YAML DSL schema it's possible to define some steps directly with the string instead of step parameters, e.g: 

```yaml
  - setExchangePattern: pattern
  - convertBodyTo: string
  -  removeHeader: header
  - removeProperties: props.*
  - toD: direct:a
```  instead of 
```yaml
  - setExchangePattern: 
       pattern:inOnly
  - convertBodyTo: 
       type: string
  -  removeHeader: 
         name: header
  - removeProperties: 
        pattern: props.*
  - toD: 
       uri:direct:a
```

It seems that Kaoto is recognising only steps with uri, and expressions and dataformat.

This might be quite hard but I believe I'd be nice to recognise steps which required attributes can be defined using string.

Related to: https://github.com/KaotoIO/kaoto/issues/2084

### Steps to Reproduce the Bug or Issue

1. in the source code view paste some route with string defied steps eg:
 ```yaml
- route:
    id: route-2517
    from:
      id: from-2423
      uri: timer
      parameters:
        period: "1000"
        timerName: template
      steps:
        - log: ${body}
        - loadBalance:
            steps:
              - to: direct:a
            customLoadBalancer: new
        - setExchangePattern: inOnly
        - convertBodyTo: string
```
2. check the convertBodyTo, customLoadBalancer, setExchangePattern in the visualisation form.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
There's still an issue that we need to consider for the next PR:

Starting with this XML route
```xml
<camel>
  <route id="route-8014">
    <from id="from-8738" uri="timer:template?period=1000"/>
  </route>
  <beans>
    <bean name="hola" type="org.slf4j.Logger">
      <constructors>
        <constructor value="value-0"/>
        <constructor value="value-1"/>
      </constructors>
    </bean>
  </beans>
</camel>
```

Going to YAML, we see this:
```yaml
- route:
    id: route-8014
    from:
      id: from-8738
      uri: timer:template?period=1000
      steps: []
- beans:
    - constructors:
        "0": value-0
        "1": value-1
      name: hola
      type: org.slf4j.Logger
```

Notice how the URI in the `from` tag is not parsed into parameters.
