### ISSUE TITLE
Beans only have name and type in route export

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto#2093]
### Please describe the feature that you want to propose

When exporting the documentation for a route, the beans only have `name` and `type` properties in the exported document, even though they might have more properties specified.

Use e.g the route:
```
- route:
    id: camel-route
    from:
      uri: timer
      parameters:
        timer: "#test"
        timerName: test
      steps:
        - to:
            uri: log:test
- beans:
    - builderClass: test
      builderMethod: test
      destroyMethod: test
      factoryBean: test
      factoryMethod: test
      initMethod: test
      name: test
      type: java.util.Timer
```

The exported documentation contains only:

![Image](https://github.com/user-attachments/assets/7485bb5a-5f37-4546-8bf0-8438f388f1bb)
