### ISSUE TITLE
XML-like text breaks the Route documentation md file

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#2096]
### Please describe the task that needs to be done

When using a XML-like text in the `expression` field of `setBody`, it seems the markdown library is not able to parse it properly.

How to reproduce:
Using the following route:
```yaml
- route:
    id: route-1108
    description: Get Account
    from:
      id: from-2909
      uri: rest
      parameters:
        method: get
        path: /account
      steps:
        - bean:
            method: address()
            ref: fakerInstance
        - setBody:
            simple:
              expression: >
                <Account>
                    <Name>${bean:fakerInstance.name().fullName()}</Name>
                    <Address>${body.streetName()}, ${body.buildingNumber()}</Address>
                    <City>${body.city()}</City>
                    <Country>${body.country()}</Country>
                </Account>
              resultType: org.w3c.dom.Document
        - to:
            uri: log
            parameters:
              loggerName: InfoLogger
              multiline: true
              showBodyType: true
              style: Fixed
            disabled: false
```

Export the Route documentation and notice how the bottom part of the table looks strange

![Image](https://github.com/user-attachments/assets/a2103a81-aaee-42fc-a643-4c1d25bffe04)
