### ISSUE TITLE
Replaced Route on the Source code is hidden by default on the Design page

### ISSUE THREAD

**Issue by shivamG640** [KaotoIO/kaoto#2214]
### Describe the Bug

If I go to source code and paste a complete new route definition. Then returning back to the design page, the route is hidden by default.
This also affect the Vscode-kaoto.

### Steps to Reproduce the Bug or Issue

1. On the design page, create a new route.
2. move to soure code page, replace the existing route definition with new one.
Paste the following code:
```
- route:
    from:
      uri: timer:yaml
      parameters:
        period: "1000"
      steps:
        - setBody:
            simple: Hello Camel from ${routeId}
        - log: ${body}
```

3. move back to design page.

### Screenshots or Videos

https://github.com/user-attachments/assets/15a940d4-6d95-444b-b7d7-bf7b20678103

### Platform

- OS: Linux
- Browser: Chrome
