### ISSUE TITLE
Azure-related icons seems small

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#2215]
### Please describe the task that needs to be done

![Image](https://github.com/user-attachments/assets/88ad6872-a2c5-48ab-a96c-d5a8d62829c4)

![Image](https://github.com/user-attachments/assets/dd283ef4-5d89-4d45-a076-e7c94ef51585)

**Comment by lordrip** [comment]
Hint: 
```css
.custom-node__container__image img {
  max-width: 100%;
  height: 100%;
}
```
