### ISSUE TITLE
Support RouteTemplate and TemplatedRoute

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#2280]
### Please describe the feature that you want to propose

Currently they are ignored
```yaml
- routeTemplate:
    id: "myTemplate"
    from:
      uri: "direct:{{directName}}"
      steps:
        - process:
            ref: "{{myProcessor}}"
        - to: "mock:result"
- templatedRoute:
    routeId: "myRoute"
    routeTemplateRef: "myTemplate"
    parameters:
      - name: "directName"
        value: "foo"
    beans:
      - name: "myProcessor"
        type: "${MyUppercaseProcessor.class.name}" 
        scriptLanguage: "groovy"
        script: |
          new ${MyUppercaseProcessor.class.name}()
- templatedRoute:
    routeId: "myRoute2"
    routeTemplateRef: "myTemplate"
    parameters:
      - name: "directName"
        value: "foo2"
    beans:
      - name: "myProcessor"
        type: "org.apache.camel.Processor"
        scriptLanguage: "groovy"
        script: "new ${MyUppercaseProcessor.class.name}()"      
```

**Comment by lordrip** [comment]
An example using parameters

```yaml
- routeTemplate:
    id: myTemplate
    parameters:
      - name: directName
        defaultValue: "hola"
    from:
      uri: direct:{{directName}}
      steps:
        - process:
            ref: "{{myProcessor}}"
        - to: mock:result
```

Docs: https://camel.apache.org/manual/route-template.html
