### ISSUE TITLE
In Choice, second when is inserted at the wrong place in code

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto#446]
### Describe the Bug

In `Choice`, second `when` is inserted at the wrong place in code

### Steps to Reproduce the Bug or Issue

1. Add a Choice
2. Add another when
--> check source code, 2 whens are nested

```yaml
- route:
    from:
      uri: timer:yaml?period=3s
      steps:
        - choice:
            id: choice-9864
            when:
              - when:
                  id: when-3147
              - id: when-3590
                simple: ${header.foo} == 1
                steps:
                  - log:
                      id: log-2742
                      message: ${body}
            otherwise:
              id: otherwise-1665
              steps:
                - log:
                    id: log-1256
                    message: ${body}
      parameters:
        exceptionHandler: {}
        timer: {}
    id: route-1500
 ```

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/1105127/3f2e5cc7-b68f-48c7-9a3b-d4b39df5efae

### Platform

- OS: Fedora
- Browser: Firefox
- Version: online
