### ISSUE TITLE
Support routeConfiguration

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#492]
### Please describe the feature that you want to propose

We're missing several configurations support such as `routeConfiguration`, `restConfiguration`, `errorHandler`, `onException` and etc.
https://github.com/apache/camel/blob/2e7578c9426bb327e0ca8c43b4a93063d70b946e/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json#L15611-L15649

`routeTemplate` and `templatedRoute` would be another visual entities to show as a diagram. There might be more that has `steps` inside.

#### Update
This issue now focuses on `routeConfiguration`. Filed separate issues for others. Since `routeConfiguration` has `errorHandler` and `onException` as its property, #560 and #561 are **little bit** less important once `routeConfiguration` is supported. 
- #560 
- #561 
- #562
- #563 

#### Update 2
Putting on hold. Not a few of `routeConfiguration` properties have `steps` inside, therefore they need flow visualization. We need to figure out how to visualize those sub routes configuration in the canvas.
- intercept
- interceptFrom
- interceptSendToEndpoint
- onCompletion
- onException

#### An example route
```yaml
- routeConfiguration:
    errorHandler:
      defaultErrorHandler:
        level: ERROR
    intercept:
      - intercept:
          steps:
            - log: "intercept1"
      - intercept:
          steps:
            - log: "intercept2"
    interceptFrom:
      - interceptFrom:
          uri: "direct:start1"
          steps:
            - log: "interceptFrom1"
      - interceptFrom:
          uri: "direct:start2"
          steps:
            - log: "interceptFrom2"
    interceptSendToEndpoint:
      - interceptSendToEndpoint:
          uri: "direct:start1"
          steps:
            - log: "interceptSendToEndpoint1"
      - interceptSendToEndpoint:
          uri: "direct:start2"
          steps:
            - log: "interceptSendToEndpoint2"
    onCompletion:
      - onCompletion:
          steps:
            - log: "onCompletion1"
      - onCompletion:
          steps:
            - log: "onCompletion2"
    onException:
      - onException:
          handled:
            constant: "true"
          exception:
            - "java.lang.Exception"
          steps:
            - log: "onException1"
      - onException:
          handled:
            constant: "true"
          exception:
            - "java.io.IOException"
          steps:
            - log: "onException2"

- route:
    from:
      uri: "timer:foo"
      steps:
        - log: "bar"
        - to: "direct:start1"
        - to: "direct:start2"
- route:
    from:
      uri: "direct:start1"
      steps:
        - log: "direct-start1"
- route:
    from:
      uri: "direct:start2"
      steps:
        - log: "direct-start2"
```
