### ISSUE TITLE
Support `saga` eip

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto#504]
### Please describe the feature that you want to propose

There're roughly 2 things to do

1. It's a branching step, need a special handling just like filter. In addition to that, it has 2 parameters `compensation` and `completion`, both have `uri` and `parameters` to route to the arbitrary endpoint. We might be able to make these `compensation` and `completion` to be an artificial node/step in the canvas, then it will look similar with doTry-doCatch-doFinally.
2. `option` property is key-value pairs where the value is expression structure
```yaml
- saga:
    option:
      - key: prop1
        expression:
          simple:
            expression: ${header.prop1}
      - key: prop2
        expression:
          jq:
            expression: header.prop2
      - key: prop3
        expression:
          jsonpath:
            expression: /body/prop3
```
It will be too chaotic to have a key-expression table in the right drawer form and show `ExpressionEditor` for each entry. It needs some layout separation.
