### ISSUE TITLE
Offer a reformat feature

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto#96]
### Context
Currently, there are changes in the Camel YAML Schema, going from `kebab-case` to `camelCase` and this might be transformed using automated process directly from `kaoto-next`

### Goal
The goal of this issue is to provide a `reformat` button to the source code editor that:
- [ ] Transform from `kebab-case` to `camelCase`
- [ ] Transform URI query parameters to property objects
- [ ] Use the recommended `to:` syntax

**Comment by igarashitm** [comment]
Aligning expression dialect would fall into here as well

```yaml
- when:
    simple: ${header.foo} == 'foo'
```
```yaml
 - when:
     simple:
       expression: '${header.foo} == 'foo'
```
```yaml
 - when:
     expression:
       simple: ${header.foo} == 'foo'
```
```yaml
 - when:
     expression:
       simple:
         expression: ${header.foo} == 'foo'
```
